info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T09:23:48.699Z"}
info: Connected to the database. {"timestamp":"2022-06-24T09:23:54.055Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T09:58:15.018Z"}
info: Connected to the database. {"timestamp":"2022-06-24T09:58:32.858Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T09:59:40.445Z"}
info: Connected to the database. {"timestamp":"2022-06-24T09:59:46.618Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T10:08:39.203Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-06-24T10:09:09.224Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T10:10:27.272Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-06-24T10:10:57.297Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T10:28:16.084Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-06-24T10:28:46.114Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T10:29:36.384Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-06-24T10:30:06.414Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T10:33:52.764Z"}
error: Could not connect to the database. URI does not have hostname, domain name and tld {"name":"MongoParseError","stack":"MongoParseError: URI does not have hostname, domain name and tld\n    at parseSrvConnectionString (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongodb\\lib\\core\\uri_parser.js:51:21)\n    at parseConnectionString (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongodb\\lib\\core\\uri_parser.js:611:12)\n    at connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongodb\\lib\\operations\\connect.js:283:3)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongodb\\lib\\mongo_client.js:284:5\n    at maybePromise (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongodb\\lib\\utils.js:692:3)\n    at MongoClient.connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongodb\\lib\\mongo_client.js:280:10)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\connection.js:836:12\n    at new Promise (<anonymous>)\n    at NativeConnection.Connection.openUri (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\connection.js:832:19)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\src\\config\\/database.js:12:20)","timestamp":"2022-06-24T10:33:52.792Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T10:34:49.412Z"}
error: Could not connect to the database. Invalid connection string {"name":"MongoParseError","stack":"MongoParseError: Invalid connection string\n    at parseConnectionString (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongodb\\lib\\core\\uri_parser.js:585:21)\n    at connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongodb\\lib\\operations\\connect.js:283:3)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongodb\\lib\\mongo_client.js:284:5\n    at maybePromise (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongodb\\lib\\utils.js:692:3)\n    at MongoClient.connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongodb\\lib\\mongo_client.js:280:10)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\connection.js:836:12\n    at new Promise (<anonymous>)\n    at NativeConnection.Connection.openUri (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\connection.js:832:19)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)","timestamp":"2022-06-24T10:34:49.438Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T10:37:46.022Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-06-24T10:38:16.056Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T10:38:47.721Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-06-24T10:39:17.766Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T10:41:14.327Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\ankan\\My_Fundo\\My_Fundoo_Project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-06-24T10:41:44.350Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T18:25:18.930Z"}
info: Connected to the database. {"timestamp":"2022-06-24T18:25:27.565Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-24T18:27:05.787Z"}
info: Connected to the database. {"timestamp":"2022-06-24T18:27:13.173Z"}
